# Generated by Django 4.1.4 on 2023-01-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_crmuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='team',
            field=models.SmallIntegerField(choices=[(0, 'Management'), (1, 'Ventes'), (2, 'Support')]),
        ),
    ]
