# Generated by Django 4.1.4 on 2023-01-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_client_email_alter_client_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sales_contact',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='sales_contact',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='support_contact',
            new_name='assignee',
        ),
    ]
