# Generated by Django 4.1.4 on 2023-01-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_rename_sales_contact_client_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(limit_choices_to={'assignee__isnull': False}, on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=None, null=True, verbose_name='Nombre de participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
    ]
