# Generated by Django 4.1.4 on 2023-01-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_contract_client_alter_event_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Nombre de participants'),
        ),
    ]
