# Generated by Django 4.1.4 on 2023-01-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_alter_client_company_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due on'),
        ),
    ]
