# Generated by Django 4.1.4 on 2023-01-05 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_alter_contract_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, to='CRM.contract'),
        ),
    ]
