# Generated by Django 4.1.4 on 2023-01-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_alter_event_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(limit_choices_to={'event__isnull': True, 'status': 1}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CRM.contract'),
        ),
    ]
