# Generated by Django 4.1.4 on 2023-01-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Création')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('age', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), ('phone__isnull', False), ('mobile__isnull', False), _connector='OR'), name='contact'),
        ),
    ]
