# Generated by Django 4.1.4 on 2023-01-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_remove_client_contact_client_one contact'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 1), ('payment_due__isnull', False)), models.Q(('status', 0), ('payment_due__isnull', True)), _connector='OR'), name='date of payment when signed', violation_error_message='A contract must have a date of payment only once signed'),
        ),
    ]
