# Generated by Django 4.1.4 on 2023-01-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0014_contract_date of payment when signed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='one contact',
        ),
    ]
