# Generated by Django 4.1.4 on 2023-01-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0015_remove_client_one contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), ('phone__isnull', False), ('mobile__isnull', False), _connector='OR'), name='one contact', violation_error_message='You must add a phone, a mobile or a mail.'),
        ),
    ]
