# Generated by Django 4.1.4 on 2023-01-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0017_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(blank=True, null=True, verbose_name='Due on'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'On Going'), (1, 'Canceled'), (2, 'Done')], default=0, verbose_name='Status'),
        ),
    ]
