# Generated by Django 4.1.4 on 2023-01-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0019_event_created_time_event_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(limit_choices_to={'assignee__isnull': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.client'),
        ),
    ]
