# Generated by Django 4.1.4 on 2023-01-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0020_alter_contract_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'team': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='assignee',
            field=models.ForeignKey(limit_choices_to={'team': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(limit_choices_to={'assignee__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='CRM.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'team': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
